apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: easi-ingress
  namespace: enterprisearchitecture-pnpbj
spec:
  entryPoints: []
  routes:
  - kind: Rule
    match: Host(`easi.dfds.cloud`) && PathPrefix(`/api`)
    middlewares:
      - name: strip-api-prefix
    services:
    - kind: Service
      name: easi-backend
      namespace: enterprisearchitecture-pnpbj
      port: external
  - kind: Rule
    match: Host(`easi.dfds.cloud`)
    services:
    - kind: Service
      name: easi-frontend
      namespace: enterprisearchitecture-pnpbj
      port: external
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-api-prefix
  namespace: enterprisearchitecture-pnpbj
spec:
  stripPrefix:
    prefixes:
    - /api
